from typing import Protocol, TypeVar

T_contra = TypeVar("T_contra", contravariant=True)

class Writer(Protocol[T_contra]):
    @property
    def desired_size(self) -> int | None: ...
    def release_lock(self) -> None: ...
    async def ready(self) -> None: ...
    async def write(self, data: T_contra) -> None: ... 
    async def close(self) -> None: ...
    async def abort(self, reason: Exception) -> None: ...

